version: '3'
services:
  web:
    image: odoo:11
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  lb:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web
    environment:
      - VIRTUAL_HOST
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    links:
      - db
volumes:
  odoo-web-data:
  odoo-db-data:
